#!/bin/sh

AWK=/usr/bin/awk
MKFIFO=/usr/bin/mkfifo
MKTEMP=/usr/bin/mktemp
RM=/bin/rm

trap atexit EXIT
trap 'result=$?; trap - EXIT; atexit; exit ${result}' SIGHUP SIGINT SIGQUIT SIGABRT SIGALRM SIGTERM
atexit() {
	[ "x${workdir}" != "x" -a -d "${workdir}" ] && ${RM} -Rf "${workdir}"
}

workdir="`${MKTEMP} -d`"
bcfifo="${workdir}/bcfifo"
${MKFIFO} "${bcfifo}"

${AWK} -v "m55_do_expr_fifo=${bcfifo}" -f m55.awk "$@"
